services:
  web:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
